spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    

# 定义上传以及访问资源路径
resource:
  sftp:
    path: /var/resource/tcmanage/resource
    url-prefix: http://resource.hzcoding.com/resource
    
# logging:
#   file: session_switch.log